# Generated by Django 3.1.2 on 2021-06-01 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceleration',
            name='sleeptime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 14, 29, 15, 233004, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sound',
            name='sleeptime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 14, 29, 15, 233191), null=True),
        ),
    ]
